### PR TITLE
Add latex linting support.

### PR DESCRIPTION
**Pull request by PerilousBooklet**

### CODE REVIEW

**Comment by PerilousBooklet** [comment]
I forgot to modify the regular expressions.

**Comment by jgmdev** [comment]
Could you also bump the manifest.json plugin version to 0.3.1?

**Comment by PerilousBooklet** [comment]
Sure.

**Comment by jgmdev** [comment]
> I forgot to modify the regular expressions.
> I'll fix it as soon as I can.

Let me know when this PR is tested and working and I will merge it. Otherwise I could install the latex linter myself and give it a test when I get some time.

**Comment by PerilousBooklet** [comment]
It's going to take me a while before I can fix the regex, because I need to learn how those settings work first and I still have exams, but if you could take a look at it, it would be a big help.

**Comment by PerilousBooklet** [comment]
I'm closing this PR, because I recently found out that `texlab` already includes an integrated linter.

**Pull request closed without merging**
